#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZuydApp.Droid.Resource", IsApplication=true)]

namespace ZuydApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_down = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ProgressBarStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int zuyd_logo = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int BtnLoginLogin = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int BtnRegisterLogin = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int CbxRemberLogin = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int PgbLogin = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int TxtEmailLogin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int TxtPasswordLogin = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int btnCreateRegister = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int button1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int button2 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int button3 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int button4 = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int progressBarRegister = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int txtEmailRegister = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int txtNumberRegister = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int txtPassword1Register = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int txtPassword2Register = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Register = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int dialog_animation = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
